In [2]:
import numpy as np

In [3]:
simple_list = [1,2,3] #create simple list

In [4]:
np.array(simple_list) #create simple 1-d vector

array([1, 2, 3])

In [5]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]] 

In [6]:
np.array(list_of_lists) #create nd matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10) #create 1-D vector exclusive of 2 argument

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,21,5) #create 1-D vector exclusive of 2 argument and step size of 3 argument

array([ 0,  5, 10, 15, 20])

In [10]:
np.linspace(0,20,10) #return evenly spaced samples on given time interval 

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [11]:
 np.eye(5) #create identity matrix, all diagnols will have value = 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(3,2) #create random valued(uniformly distributed) matrix with specified dimensions

array([[0.54021593, 0.0543576 ],
       [0.78738879, 0.27145852],
       [0.29147274, 0.46158167]])

In [13]:
np.random.randn(2,3) #create random valued(standard distribution) matrix with specified dimensions

array([[ 1.4499611 ,  1.05312962, -0.67370111],
       [ 0.41498346, -0.28645587, -1.73129837]])

In [14]:
np.random.randint(10,30) #fetch random int within given range exclusive of 2 argument

25

In [15]:
np.random.randint(10,20,5) #create 1-D vector with given range and step value

array([12, 13, 13, 18, 10])

In [17]:
sample_array = np.arange(5,30)
rand_array = np.random.randint(0,50,20)
sample_array.reshape(5,5)      #reshape 1-D vector to matrix of desired dimension

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [18]:
sample_array.dtype  #return data type 

dtype('int64')

In [19]:
rand_array.dtype

dtype('int64')

In [20]:
rand_array.T  #returns transpose of a given matrix

array([25,  6,  0, 28, 26, 27, 17,  3, 41,  6, 23,  5, 13, 22, 11,  0, 16,
        9, 24,  9])

In [22]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [23]:
a.transpose() #returns transpose of a given matrix

array([[1, 3],
       [2, 4]])

In [24]:
sample_array = np.arange(10,31)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [25]:
subset_sample_array = sample_array[0:7] #creating view not the copy of original array
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [26]:
subset_sample_array[:] = 1001 #broadcasting

In [27]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [28]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30])

In [31]:
sample_matrix = np.array(([50,20,123], [20,40,50], [40,80,90]))
sample_matrix

array([[ 50,  20, 123],
       [ 20,  40,  50],
       [ 40,  80,  90]])

In [32]:
sample_matrix[0][2] #indexing matrix via 2d location points

123

In [34]:
sample_matrix[0,2] #indexing matrix via 2d location points

123

In [35]:
sample_matrix[2,:] #slicing matrix (3rd row and all the columns)

array([40, 80, 90])

In [36]:
sample_matrix = np.array(([50,20,123,44], [20,40,50,46], [40,80,90,40], [20,50,46,67]))
sample_matrix

array([[ 50,  20, 123,  44],
       [ 20,  40,  50,  46],
       [ 40,  80,  90,  40],
       [ 20,  50,  46,  67]])

In [37]:
sample_matrix[:,(1,3)]  #custom indexing (all rows,  2and 4 column)

array([[20, 44],
       [40, 46],
       [80, 40],
       [50, 67]])

In [39]:
sample_matrix = np.arange(1,31)
sample_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
sample_matrix < 15   #selection technique

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [42]:
sample_matrix[sample_matrix < 15] #selection based on condition

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.argmax(sample_matrix) #index of the max value

29

In [44]:
array = np.random.randn(6,6)
array

array([[-0.58312957, -0.16639234, -0.31297497, -0.10678023,  0.39667459,
        -0.86647025],
       [-0.16528736,  1.22959997, -0.89517661,  0.11804066, -0.86366947,
         0.5301186 ],
       [ 0.43358581, -0.75068087,  0.73563121,  2.07729479, -0.38095647,
         1.59383662],
       [-0.35076687, -0.9283554 , -0.88071924, -0.02223694, -1.00149095,
        -0.21074955],
       [-2.2071053 , -0.31384592, -0.01217169, -1.58710479,  0.05476266,
        -0.72617775],
       [-0.82291225,  0.88569205,  0.88764513, -0.29343234,  1.71513728,
         0.0858376 ]])

In [45]:
np.round(array) #rounding to nearest integer number

array([[-1., -0., -0., -0.,  0., -1.],
       [-0.,  1., -1.,  0., -1.,  1.],
       [ 0., -1.,  1.,  2., -0.,  2.],
       [-0., -1., -1., -0., -1., -0.],
       [-2., -0., -0., -2.,  0., -1.],
       [-1.,  1.,  1., -0.,  2.,  0.]])

In [46]:
np.round(array, decimals=2) #rounding to 2 decimal places

array([[-0.58, -0.17, -0.31, -0.11,  0.4 , -0.87],
       [-0.17,  1.23, -0.9 ,  0.12, -0.86,  0.53],
       [ 0.43, -0.75,  0.74,  2.08, -0.38,  1.59],
       [-0.35, -0.93, -0.88, -0.02, -1.  , -0.21],
       [-2.21, -0.31, -0.01, -1.59,  0.05, -0.73],
       [-0.82,  0.89,  0.89, -0.29,  1.72,  0.09]])

In [47]:
np.std(array) #standard deviation of whole array values

0.894287970923633

In [48]:
np.mean(array) #mean of whole array values

-0.10290917178359693

In [49]:
simple_array = np.arange(0,41)
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [50]:
np.save('simple_array', simple_array) #saving single file in working directory with given name

In [52]:
np.savez('multi_arrays.npz', a=sample_array, b=simple_array) #saving multiple vectoes as archived files

In [54]:
np.load('simple_array.npy') # loading saved file from disk

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [57]:
archive = np.load('multi_arrays.npz') #loading saved archived files and calling via variables
archive['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])